global:
  env: prod
be:
  env:
    NODE_ENV: production
  image:
    tag: prod-2c7643ee052f99c80c3353409911f24cdccc1ed1
fe:
  image:
    tag: prod-435ff8a962a19b665b96e64f753a1184a83bbf9b
ingress:
  host: tm.thangns.id.vn
externalSecret:
  secretName: tm-app-prod
