apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-secret
  namespace: monitoring

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: telegram-secret
    creationPolicy: Owner

  data:
    - secretKey: bot_token
      remoteRef:
        key: tm-app-prod
        property: TELEGRAM_BOT_TOKEN

    - secretKey: chat_id
      remoteRef:
        key: tm-app-prod
        property: TELEGRAM_CHAT_ID
