global:
  env: dev
be:
  env:
    NODE_ENV: development
  image:
    tag: dev-ae0ca54730d0ca8401cace3a42e37f522ead5341
fe:
  image:
    tag: dev-11536b8726d51e2100cea0bb85d7df1be746b77f
ingress:
  host: dev.tm.thangns.id.vn
externalSecret:
  secretName: tm-app-dev
