global:
  env: dev
be:
  image:
    tag: dev-9d5d7c4e23e0c67c7a9ea8b6ed279f294e736c37
fe:
  image:
    tag: dev-7828ea77bfa690b07fd72db23bb93868e433d569
ingress:
  host: dev.tm.thangns.id.vn
externalSecret:
  secretName: tm-app-dev
