apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tm-app-prod
        property: POSTGRES_PASSWORD
